services:
    bitbag_sylius_wishlist_plugin.context.wishlist:
        class: BitBag\SyliusWishlistPlugin\Context\WishlistContext
        public: true
        arguments:
            - "@security.token_storage"
            - "@bitbag_sylius_wishlist_plugin.repository.wishlist"
            - "@bitbag_sylius_wishlist_plugin.factory.wishlist"
            - "%wishlist_cookie_token%"
            - "%wishlist_cookie_token%"
