services:
    bitbag_sylius_wishlist_plugin.event_listener.merge_user_wishlist_items:
        class: BitBag\SyliusWishlistPlugin\EventListener\MergeUserWishlistItemsListener
        arguments:
            - "@bitbag_sylius_wishlist_plugin.repository.wishlist"
            - "@bitbag_sylius_wishlist_plugin.manager.wishlist"
            - "%wishlist_cookie_token%"
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onInteractiveLogin }
