services:
    bitbag_sylius_wishlist_plugin.form.type.add_products_to_cart:
        class: BitBag\SyliusWishlistPlugin\Form\Type\AddProductsToCartType
        arguments:
            - "@sylius.factory.add_to_cart_command"
            - "@sylius.factory.order_item"
            - "@sylius.order_item_quantity_modifier"
            - "%sylius.form.type.cart_item.validation_groups%"
        tags:
            - { name: form.type }

    bitbag_sylius_wishlist_plugin.form.type.extension.add_to_cart_type_extension:
        class: BitBag\SyliusWishlistPlugin\Form\Extension\AddToCartTypeExtension
        tags:
            - { name: form.type_extension, extended_type: Sylius\Bundle\CoreBundle\Form\Type\Order\AddToCartType }



