imports:
    - { resource: 'twig_hooks/**/*.yaml' }

sylius_order:
    resources:
        order_item:
            classes:
                controller: BitBag\SyliusWishlistPlugin\Controller\OrderItemController
